{% set name = "raspa3" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/iRASPA/RASPA3/archive/v{{ version }}.tar.gz
  sha256: 565f5e490879f67a6551cc7407201f7884ba6dc2b6543c1c61d36862b054df55

build:
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - clang-19  # [linux and osx]
    - clangxx-19  # [linux and osx]
    - clang-tools  # [linux and osx]
    - llvm-tools  # [linux and osx]
    - cmake
    - ninja
    - lld
    - libcxx-devel  # [not win]
  host:
    - libcxx  # [linux and osx]
    - libcxxabi  # [linux]
    - openblas
    - libblas
    - liblapack
    - libgomp  # [linux]
    - llvm-openmp  # [osx and win]
    - hdf5
    - zlib
    - openssl
    - libcurl
    - libaec
  run:
    - libcxx  # [linux and osx]
    - libcxxabi  # [linux]

test:
  commands:
    - raspa3 --help

about:
  home: https://github.com/iraspa/raspa3
  summary: 'A general purpose classical simulation package'
  description: |
    RASPA is a software package for simulating adsorption and 
    diffusion of molecules in flexible nanoporous materials. 
    The code implements the latest state-of-the-art algorithms 
    for Molecular Dynamics and Monte Carlo in various ensembles 
    including symplectic/measure-preserving integrators, Ewald 
    summation, Configurational-Bias Monte Carlo, Continuous 
    Fractional Component Monte Carlo, and Reactive Monte Carlo.
  license: MIT
  license_file: LICENSE.md
  doc_url: https://iraspa.github.io/RASPA3
  dev_url: https://github.com/iraspa/raspa3

extra:
  recipe-maintainers:
    - dubbelda
