{% set name = "raspa3" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://iraspa.org/wp-content/uploads/2025/03/v3.0.3.tar.gz
  sha256: a906d739d2e622435794a5de2631b6b1129f089d4baa08ddf85f183de4de13ce

build:
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - clang-tools  # [unix]
    - llvm-tools  # [unix]
    - cmake
    - ninja
    - lld
    - libcxx-devel  # [unix]
  host:
    - libcxx  # [unix]
    - libcxxabi  # [linux]
    - libgomp  # [linux]
    - llvm-openmp  # [not linux]
    - libblas
    - liblapack
    - libopenblas  # [linux]
    - hdf5
    - zlib
    - openssl
    - libcurl
    - libaec
  run:
    - libcxx  # [osx]
    - libcxxabi  # [osx]

test:
  commands:
    - raspa3 --help

about:
  home: https://github.com/iraspa/raspa3
  summary: 'A general purpose classical simulation package'
  description: |
    RASPA is a software package for simulating adsorption and 
    diffusion of molecules in flexible nanoporous materials. 
    The code implements the latest state-of-the-art algorithms 
    for Molecular Dynamics and Monte Carlo in various ensembles 
    including symplectic/measure-preserving integrators, Ewald 
    summation, Configurational-Bias Monte Carlo, Continuous 
    Fractional Component Monte Carlo, and Reactive Monte Carlo.
  license: MIT
  license_file: LICENSE.md
  doc_url: https://iraspa.github.io/RASPA3
  dev_url: https://github.com/iraspa/raspa3

extra:
  recipe-maintainers:
    - dubbelda
