azure:
  settings_win:
    variables:
      SET_PAGEFILE: 'True'
      CONDA_BLD_PATH: C:\\bld\\
      MINIFORGE_HOME: C:\Miniforge
build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
test: native_and_emulated
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
